# Generated by Django 6.0.2 on 2026-03-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
